const constants = {
  LOADING: 'LOADING',
  LOADED: 'LOADED',
  DELETING: 'DELETING',
  DELETED: 'DELETED',
  UPLOADING: 'UPLOADING',
  UPLOADED: 'UPLOADED',
  UPDATING: 'UPDATING',
  UPDATED: 'UPDATED',
  CREATING: 'CREATING',
  CREATED: 'CREATED',

  SET_DETAIL_DATA: 'SET_DETAIL_DATA'
}

export default constants
